---
- name: Verify
  hosts: all
  gather_facts: false
  become: true
  tasks:
    ## ユーザーのテスト
    - name: Get user facts
      ansible.builtin.getent:
        database: passwd
        key: redis
    - name: Assert user
      ansible.builtin.assert:
        that: getent_passwd['redis'] is defined
        fail_msg: "redis user does not exist"
        success_msg: "redis user exists"
    ## グループのテスト
    - name: Get group facts
      ansible.builtin.getent:
        database: group
        key: redis
    - name: Assert group
      ansible.builtin.assert:
        that: getent_group['redis'] is defined
        fail_msg: "redis group does not exist"
        success_msg: "redis group exists"
    ## パッケージのテスト
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Assert package
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['redis'] is defined
        fail_msg: "Redis package is not installed"
        success_msg: "Redis package is installed"
    ## サービスのテスト
    - name: Populate service facts
      ansible.builtin.service_facts:
    - name: Assert service
      ansible.builtin.assert:
        that:
          - ansible_facts.services['redis-server.service'] is defined
          - ansible_facts.services['redis-server.service']['state'] == 'running'
          - ansible_facts.services['redis-server.service']['status'] == 'enabled'
        fail_msg: "redis-server service is not running or not enabled"
        success_msg: "redis-server service is running and enabled"
    ## 待受ポートのテスト
    - name: Gather facts on listening ports
      community.general.listen_ports_facts:
        command: ss
    - name: Set assert variables
      ansible.builtin.set_fact:
        listen_tcp_posts: "{{ ansible_facts.tcp_listen | map(attribute='port') | unique | list }}"
        listen_udp_posts: "{{ ansible_facts.udp_listen | map(attribute='port') | unique | list }}"
    - name: Assert listen port
      ansible.builtin.assert:
        that:
          - 6379 in listen_tcp_posts
        fail_msg: "Redis is not listening on port 6379"
        success_msg: "Redis is listening on port 6379"
